# hash-identificacao: 95ad1541dc3d7e358068b3dd89daca8569ab9f0981774767fcdeb1165d75dbc0

# Configurações padrão disponíveis: https://docs.spring.io/spring-boot/appendix/application-properties/index.html

spring.application.name=dados-pessoais

# --- Servidor Web ---
# server.port=8080
# server.servlet.context-path=/  # Opcional: definir um contexto base para a API

# --- Jackson (serialização JSON formatada) ---
spring.jackson.serialization.INDENT_OUTPUT=true


